<?php

return [
    [
        'title' => 'Men\'s Casual Shirt',
        'keywords' => 'fashion, casual, men',
        'description' => 'High-quality casual shirt for men, perfect for everyday wear.',
        'detail' => 'This casual shirt is made from premium cotton fabric and offers a comfortable fit.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Men%27s+Casual+Shirt',
    ],
    [
        'title' => 'Women\'s Handbag',
        'keywords' => 'handbag, leather, women',
        'description' => 'Elegant leather handbag for women, spacious and stylish.',
        'detail' => 'Crafted from genuine leather, this handbag features multiple compartments and a sleek design.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Women%27s+Handbag',
    ],
    [
        'title' => 'Boy\'s Running Shoes',
        'keywords' => 'shoes, running, boys',
        'description' => 'Durable running shoes for boys, designed for comfort and performance.',
        'detail' => 'These running shoes come with a cushioned sole and breathable material for optimal performance.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Boy%27s+Running+Shoes',
    ],
    [
        'title' => 'Girl\'s Summer Dress',
        'keywords' => 'dress, summer, girls',
        'description' => 'Beautiful summer dress for girls, lightweight and breathable.',
        'detail' => 'The summer dress is made from lightweight fabric, perfect for keeping cool during hot weather.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Girl%27s+Summer+Dress',
    ],
    [
        'title' => 'Gaming Laptop',
        'keywords' => 'laptop, gaming, high-performance',
        'description' => 'High-performance gaming laptop with advanced graphics and processing power.',
        'detail' => 'Equipped with the latest processors and graphics cards, this gaming laptop ensures a smooth gaming experience.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Gaming+Laptop',
    ],
    [
        'title' => 'Digital Camera',
        'keywords' => 'camera, digital, photography',
        'description' => 'Digital camera with high resolution, ideal for professional photography.',
        'detail' => 'Capture stunning photos with this digital camera, featuring a high-resolution sensor and various shooting modes.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Digital+Camera',
    ],
    [
        'title' => 'Smartphone',
        'keywords' => 'smartphone, mobile, tech',
        'description' => 'Latest smartphone with cutting-edge technology and sleek design.',
        'detail' => 'Experience the latest in mobile technology with this smartphone, boasting a powerful processor and a stunning display.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Smartphone',
    ],
    [
        'title' => 'Fitness Tracker',
        'keywords' => 'fitness, tracker, health',
        'description' => 'Fitness tracker to monitor your health and activity levels.',
        'detail' => 'Track your daily activity, heart rate, and sleep patterns with this advanced fitness tracker.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Fitness+Tracker',
    ],
    [
        'title' => 'Luxury Watch',
        'keywords' => 'watch, luxury, timepiece',
        'description' => 'Luxury watch with timeless design and superior craftsmanship.',
        'detail' => 'This luxury watch combines elegant design with precise timekeeping, making it a perfect accessory for any outfit.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Luxury+Watch',
    ],
    [
        'title' => 'Diamond Necklace',
        'keywords' => 'necklace, diamond, jewelry',
        'description' => 'Stunning diamond necklace, a perfect piece of jewelry for special occasions.',
        'detail' => 'Adorn yourself with this exquisite diamond necklace, featuring a brilliant-cut diamond set in a timeless design.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Diamond+Necklace',
    ],
    [
        'title' => 'Bluetooth Speaker',
        'keywords' => 'speaker, bluetooth, portable',
        'description' => 'Portable Bluetooth speaker with high-quality sound.',
        'detail' => 'Enjoy music on the go with this compact Bluetooth speaker, offering excellent sound quality and long battery life.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Bluetooth+Speaker',
    ],
    [
        'title' => 'Wireless Earbuds',
        'keywords' => 'earbuds, wireless, audio',
        'description' => 'Wireless earbuds with superior sound and comfort.',
        'detail' => 'Experience true wireless freedom with these high-quality earbuds, featuring excellent sound and a comfortable fit.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Wireless+Earbuds',
    ],
    [
        'title' => '4K Ultra HD TV',
        'keywords' => 'tv, 4k, ultra hd',
        'description' => 'Stunning 4K Ultra HD TV with vibrant colors and sharp detail.',
        'detail' => 'Upgrade your home entertainment system with this 4K Ultra HD TV, offering a crystal-clear picture and advanced features.',
        'image' => 'https://via.placeholder.com/640x480.png?text=4K+Ultra+HD+TV',
    ],
    [
        'title' => 'Gaming Console',
        'keywords' => 'gaming, console, entertainment',
        'description' => 'Next-gen gaming console with immersive gameplay.',
        'detail' => 'Dive into the world of gaming with this powerful console, delivering stunning graphics and smooth gameplay.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Gaming+Console',
    ],
    [
        'title' => 'Electric Toothbrush',
        'keywords' => 'toothbrush, electric, dental',
        'description' => 'Electric toothbrush for superior oral care.',
        'detail' => 'Keep your teeth clean and healthy with this advanced electric toothbrush, featuring multiple cleaning modes.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Electric+Toothbrush',
    ],
    [
        'title' => 'Smart Home Hub',
        'keywords' => 'smart home, hub, automation',
        'description' => 'Smart home hub for seamless automation.',
        'detail' => 'Control all your smart home devices with ease using this centralized hub, compatible with various platforms.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Smart+Home+Hub',
    ],
    [
        'title' => 'Drone with Camera',
        'keywords' => 'drone, camera, aerial',
        'description' => 'High-performance drone with HD camera.',
        'detail' => 'Capture stunning aerial footage with this drone, featuring a high-definition camera and stable flight performance.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Drone+with+Camera',
    ],
    [
        'title' => 'Robot Vacuum Cleaner',
        'keywords' => 'vacuum, robot, cleaner',
        'description' => 'Robot vacuum cleaner for effortless cleaning.',
        'detail' => 'Keep your home spotless with this intelligent robot vacuum cleaner, offering powerful suction and smart navigation.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Robot+Vacuum+Cleaner',
    ],
    [
        'title' => 'Portable Power Bank',
        'keywords' => 'power bank, portable, charger',
        'description' => 'Portable power bank with high capacity.',
        'detail' => 'Never run out of battery on the go with this compact and powerful power bank, perfect for charging your devices.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Portable+Power+Bank',
    ],
    [
        'title' => 'Noise Cancelling Headphones',
        'keywords' => 'headphones, noise cancelling, audio',
        'description' => 'Noise cancelling headphones with superior sound.',
        'detail' => 'Experience immersive audio with these noise cancelling headphones, featuring excellent sound quality and comfort.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Noise+Cancelling+Headphones',
    ],
    [
        'title' => 'Smartwatch',
        'keywords' => 'smartwatch, wearable, tech',
        'description' => 'Advanced smartwatch with fitness tracking.',
        'detail' => 'Stay connected and track your fitness with this stylish smartwatch, offering various health monitoring features.',
        'image' => 'https://via.placeholder.com/640x480.png?text=Smartwatch',
    ],
];
